# Generated by Django 5.0.4 on 2024-04-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autobranch',
            name='manager',
        ),
    ]
